# Generated by Django 4.0.2 on 2022-02-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=15, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('program', models.CharField(blank=True, max_length=500, null=True)),
                ('bootcamp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tech_stack', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('training_period', models.IntegerField(blank=True, choices=[(1, '1개월 미만'), (2, '1개월~3개월 미만'), (3, '3개월~6개월 미만'), (4, '6개월 이상')], null=True)),
                ('accept', models.IntegerField(blank=True, choices=[(1, '모집중'), (2, '모집예정'), (3, '모집완료')], null=True)),
                ('apply_start', models.CharField(blank=True, max_length=100, null=True)),
                ('apply_end', models.CharField(blank=True, max_length=100, null=True)),
                ('on_offline', models.IntegerField(blank=True, choices=[(1, 'Online'), (2, 'Offline'), (3, 'Both')], null=True)),
                ('place', models.IntegerField(blank=True, choices=[(1, '없음'), (2, '서울'), (3, '경기'), (4, '대구'), (5, '부산'), (6, '울산'), (7, '광주'), (8, '대전'), (9, '경북'), (10, '경남'), (11, '전북'), (12, '전남'), (13, '강원'), (14, '충남')], null=True)),
                ('apply_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('apply_course', models.IntegerField(blank=True, choices=[(1, '없음'), (2, '코테'), (3, '지원서'), (4, '인터뷰'), (5, '코테 + 지원서'), (6, '코테 + 인터뷰'), (7, '지원서 + 인터뷰'), (8, '코테 + 지원서 + 인터뷰'), (9, '적성검사')], null=True)),
                ('k_digital', models.IntegerField(blank=True, choices=[(1, '국민내일배움카드 X'), (2, '국민내일배움카드 필수'), (3, '국민내일배움카드 선택사항')], null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchBootCampDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
