# Generated by Django 4.0.2 on 2022-02-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BootCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=12)),
                ('brand_name', models.CharField(max_length=100)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('bootcamp_name', models.CharField(max_length=100)),
                ('tech_stack', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('training_period', models.CharField(blank=True, max_length=1, null=True)),
                ('accept', models.CharField(blank=True, max_length=1, null=True)),
                ('apply_start', models.DateTimeField(blank=True, null=True)),
                ('apply_end', models.DateTimeField(blank=True, null=True)),
                ('on_offline', models.CharField(blank=True, max_length=1, null=True)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('apply_condition', models.CharField(blank=True, max_length=1, null=True)),
                ('apply_course', models.CharField(blank=True, max_length=1, null=True)),
                ('k_digital', models.CharField(blank=True, max_length=1, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
