# Generated by Django 4.0.2 on 2022-02-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
