# Generated by Django 4.0.2 on 2022-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0002_alter_bootcamp_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='note',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
