# Generated by Django 4.0.2 on 2022-02-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0005_alter_bootcamp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
