# Generated by Django 4.0.2 on 2022-02-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0006_alter_bootcamp_apply_end_alter_bootcamp_apply_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
