# Generated by Django 4.0.2 on 2022-02-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0008_alter_bootcamp_apply_end_alter_bootcamp_apply_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
