# Generated by Django 4.0.2 on 2022-02-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0009_alter_bootcamp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='accept',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_condition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_course',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='k_digital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='on_offline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='training_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
