# Generated by Django 4.0.2 on 2022-02-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0012_alter_bootcamp_apply_end_alter_bootcamp_apply_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='bootcamp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='company_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
