# Generated by Django 4.0.2 on 2022-02-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0014_alter_bootcamp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
