# Generated by Django 4.0.2 on 2022-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0015_bootcamp_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
