# Generated by Django 4.0.2 on 2022-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0016_alter_bootcamp_apply_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='company_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
