# Generated by Django 4.0.2 on 2022-02-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0017_alter_bootcamp_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
