# Generated by Django 4.0.2 on 2022-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0018_alter_bootcamp_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='tech_stack',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Jupyter', 'Jupyter'), ('Django', 'Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('Ruby', 'Ruby'), ('JQuery', 'JQuery'), ('React', 'React'), ('Docker', 'Docker'), ('Android', 'Android'), ('Azure', 'Azure'), ('R', 'R'), ('JSP', 'JSP'), ('Ajax', 'Ajax'), ('Spring Boot', 'Spring Boot'), ('Json', 'Json'), ('Arduino', 'Arduino'), ('C++', 'C++'), ('Linux', 'Linux'), ('C', 'C'), ('C#', 'C#'), ('Unix', 'Unix'), ('DB', 'DB'), ('Git', 'Git'), ('SQL', 'SQL'), ('GitHub', 'GitHub'), ('React Native', 'React Native'), ('Kotlin', 'Kotlin'), ('XML', 'XML'), ('Swift', 'Swift'), ('Unitiy', 'Unitiy'), ('KoNLpy', 'KoNLpy'), ('PyTorch', 'PyTorch'), ('Cpp', 'Cpp'), ('LinuxCLI', 'LinuxCLI'), ('Elasticsearch', 'Elasticsearch'), ('Spark', 'Spark'), ('Hadoop', 'Hadoop'), ('Tensorflow', 'Tensorflow'), ('JDBC', 'JDBC'), ('JPA', 'JPA'), ('AWS', 'AWS'), ('Vanilla JS', 'Vanilla JS'), ('Firebase', 'Firebase'), ('Vue', 'Vue'), ('Oracle', 'Oracle'), ('Node.JS', 'Node.JS'), ('Mybatis', 'Mybatis'), ('Mongo DB', 'Mongo DB'), ('Vue.JS', 'Vue.JS'), ('Keras', 'Keras'), ('Gcp', 'Gcp'), ('HTTP', 'HTTP'), ('DOM', 'DOM'), ('Flask', 'Flask'), ('Typescript', 'Typescript'), ('MySQL', 'MySQL'), ('PHP', 'PHP'), ('Kubernes', 'Kubernes'), ('Klaytn', 'Klaytn'), ('Excel', 'Excel'), ('ROKIT Brick', 'ROKIT Brick'), ('Nest', 'Nest'), ('AI', 'AI'), ('PM', 'PM'), ('Block Chain', 'Block Chain'), ('Dogma', 'Dogma'), ('Sketch', 'Sketch')], max_length=100, null=True),
        ),
    ]
