# Generated by Django 4.0.2 on 2022-02-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0019_alter_bootcamp_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='accept',
            field=models.IntegerField(blank=True, choices=[(1, '모집중'), (2, '모집예정'), (3, '모집완료')], null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='apply_course',
            field=models.IntegerField(blank=True, choices=[(1, '없음'), (2, '코테'), (3, '지원서'), (4, '인터뷰'), (5, '코테 + 지원서'), (6, '코테 + 인터뷰'), (7, '지원서 + 인터뷰'), (8, '코테 + 지원서 + 인터뷰'), (9, '적성검사')], null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='k_digital',
            field=models.IntegerField(blank=True, choices=[(1, '국민내일배움카드 X'), (2, '국민내일배움카드 필수'), (3, '국민내일배움카드 선택사항')], null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='on_offline',
            field=models.IntegerField(blank=True, choices=[(1, 'Online'), (2, 'Offline'), (3, 'Both')], null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='place',
            field=models.IntegerField(blank=True, choices=[(1, '없음'), (2, '서울'), (3, '경기'), (4, '대구'), (5, '부산'), (6, '울산'), (7, '광주'), (8, '대전'), (9, '경북'), (10, '경남'), (11, '전북'), (12, '전남'), (13, '강원'), (14, '충남')], null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='program',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='training_period',
            field=models.IntegerField(blank=True, choices=[(1, '1개월 미만'), (2, '1개월~3개월 미만'), (3, '3개월~6개월 미만'), (4, '6개월 이상')], null=True),
        ),
    ]
