# Generated by Django 3.2.12 on 2022-02-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0020_alter_bootcamp_accept_alter_bootcamp_apply_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBootCampDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
