# Generated by Django 4.0.2 on 2022-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0021_searchbootcampdto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='image_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
