# Generated by Django 4.0.2 on 2022-02-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BootCamp', '0022_bootcamp_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bootcamp',
            name='count',
        ),
    ]
